### ISSUE TITLE
package.json is required

### ISSUE THREAD

**Issue by vdsbenoit** [kenchan0130/markdown-to-atlassian-wiki-markup-cli#135]
If I try to run the CLI command with a file path I get this error : 
````sh
markdownToAtlassianWikiMarkup readme.md
ENOENT: no such file or directory, open 'C:\Users\myusername\workspace\myproject\package.json'
````
My project is not a js project. It looks like it only works in a node project directory (as package.json is required).
 
I found a workaround : 
- create a package.json file
- write `{}` in it

However, this is not convenient at all as I have markdown files a bit everywhere on my computer. Could you fix it? 🙏 

I'm on Windows and I have installed the package globally through npm.

**Comment by kenchan0130** [comment]
@vdsbenoit 

I think the problem here has probably been fixed.
Please check with the latest version.

If you're still having problems, please reopen he

**Comment by vdsbenoit** [comment]
Thank you !

**Comment by vdsbenoit** [comment]
I confirm it is fixed
